# Generated by Django 4.2.4 on 2023-08-09 16:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_bill_customerdetails_employeeinfo_facilities_food_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bill',
            name='customer_detail',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='base.customerdetails'),
        ),
        migrations.AddField(
            model_name='customerdetails',
            name='room',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='base.room'),
        ),
        migrations.AddField(
            model_name='employeeinfo',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='food',
            name='menu_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='base.menutype'),
        ),
        migrations.AddField(
            model_name='paymentinfo',
            name='bill',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='base.bill'),
        ),
        migrations.AlterField(
            model_name='customerdetails',
            name='gender',
            field=models.CharField(choices=[('Male', 'Male'), ('Female', 'Female'), ('Others', 'Others')], max_length=200),
        ),
        migrations.AlterField(
            model_name='employeeinfo',
            name='gender',
            field=models.CharField(choices=[('Male', 'Male'), ('Female', 'Female'), ('Others', 'Others')], max_length=200),
        ),
        migrations.AlterField(
            model_name='room',
            name='room_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='base.roomtype'),
        ),
        migrations.AlterField(
            model_name='user',
            name='user_type',
            field=models.CharField(choices=[('Frontdesk', 'Frontdesk'), ('Restaurant', 'Restaurant'), ('Accounting', 'Accounting'), ('Management', 'Management')], max_length=20),
        ),
    ]
